/**
 * Real Extracted Historical Schedules (Jan - Sep 2026)
 * Sourced directly from Brenda's handcrafted monthly survey sheets.
 */

import { parseScheduleGridData } from "./scheduleParser";
import { MonthScheduleRecord } from "./reports";

const RAW_HISTORICAL_GRIDS: { monthKey: string; rows: any[][] }[] = [
  {
    monthKey: "2026-01",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Clean 4",
        "Clean 5",
        "Clean 6",
        "Clean 7",
        "Clean 8",
        "Clean 9",
        "Clean 10",
        "Clean 11",
        "Status / Notes",
      ],
      [
        "46026.0",
        "BRUNCH",
        "",
        "Marijean",
        "Sarah",
        "",
        "Sandra",
        "Sarah",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46027.0",
        "DINNER",
        "",
        "Beth",
        "Christian",
        "Paddy",
        "Janco",
        "Monty",
        "Wei",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46030.0",
        "DINNER",
        "",
        "Frannie",
        "Rachel",
        "Saje",
        "Ian",
        "Mark L",
        "Olive",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46033.0",
        "DINNER",
        "",
        "Cy",
        "Dane",
        "Janco",
        "Beth",
        "Christian",
        "Cy",
        "46034.0",
        "Daya",
        "Jeanie",
        "Sandra",
        "Wei",
        "Donnie",
        "Marko",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
      [
        "46037.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46040.0",
        "BRUNCH",
        "",
        "Laurel",
        "Tyler",
        "",
        "Marijean",
        "Paddy",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46041.0",
        "DINNER",
        "",
        "Donnie",
        "Monty",
        "Rose",
        "Alysha",
        "Ben",
        "Kitty",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46044.0",
        "DINNER",
        "",
        "Ben",
        "Fabrice",
        "Vesanto",
        "Fabrice",
        "Rachel",
        "Vesanto",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46047.0",
        "DINNER",
        "",
        "Hillary",
        "Stacey",
        "Wally",
        "Daya",
        "Laurel",
        "Stacey",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46048.0",
        "DINNER",
        "",
        "Jeanie",
        "Ian",
        "Nancy",
        "Marko",
        "Saje",
        "Tyler",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46051.0",
        "DINNER",
        "",
        "Alysha",
        "Lorne",
        "Olive",
        "Dane",
        "Hillary",
        "Nancy",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-02",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Cook 4",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Clean 4",
        "Status / Notes",
      ],
      [
        "46054.0",
        "BRUNCH",
        "",
        "Hillary",
        "Sarah",
        "",
        "",
        "Kitty",
        "Sarah",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46055.0",
        "DINNER",
        "",
        "Beth",
        "Daya",
        "Ian",
        "Stacey",
        "Ash",
        "Saje",
        "Stacey",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
      [
        "46058.0",
        "DINNER",
        "",
        "Fabrice",
        "Marko",
        "Paddy",
        "",
        "Alysha",
        "Fabrice",
        "Mark L",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46061.0",
        "DINNER",
        "",
        "Christian",
        "Cy",
        "Saje",
        "",
        "Cy",
        "Ian",
        "Miriam",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46062.0",
        "DINNER",
        "",
        "Jeanie",
        "Sandra",
        "Wei",
        "",
        "Donnie",
        "Marko",
        "Sandra",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46065.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46068.0",
        "BRUNCH",
        "",
        "Frannie",
        "Rose",
        "",
        "",
        "Ben",
        "Olive",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46069.0",
        "DINNER",
        "",
        "Alysha",
        "Ben",
        "Donnie",
        "",
        "Daya",
        "Frannie",
        "Jeanie",
        "Miriam",
        "Handcrafted Team by Brenda",
      ],
      [
        "46072.0",
        "DINNER",
        "",
        "Marijean",
        "Monty",
        "Vesanto",
        "",
        "Hillary",
        "Mark L",
        "Vesanto",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46075.0",
        "DINNER",
        "",
        "Laurel",
        "Nancy",
        "Wally",
        "",
        "Beth",
        "Christian",
        "Laurel",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46076.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46079.0",
        "DINNER",
        "",
        "Monty",
        "Olive",
        "Rachel",
        "",
        "Kitty",
        "Paddy",
        "Rachel",
        "",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-03",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46082.0",
        "BRUNCH",
        "",
        "Alysha",
        "Jeanie",
        "",
        "Ash",
        "Marko",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46083.0",
        "DINNER",
        "",
        "Mark L",
        "Nancy",
        "Tyler",
        "Alysha",
        "Fabrice",
        "Kitty",
        "Handcrafted Team by Brenda",
      ],
      [
        "46086.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46089.0",
        "DINNER",
        "",
        "Christian",
        "Laurel",
        "Ash",
        "Christian",
        "Laurel",
        "Saje",
        "Handcrafted Team by Brenda",
      ],
      [
        "46090.0",
        "DINNER",
        "",
        "Olive",
        "Fabrice",
        "",
        "Miriam",
        "Nancy",
        "Vesanto",
        "Handcrafted Team by Brenda",
      ],
      [
        "46093.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      ["46096.0", "BRUNCH", "", "Cy", "Dane", "", "Cy", "Stacey", "", "Handcrafted Team by Brenda"],
      [
        "46097.0",
        "DINNER",
        "",
        "Donnie",
        "Frannie",
        "",
        "Daya",
        "Ian",
        "Tyler",
        "Handcrafted Team by Brenda",
      ],
      [
        "46100.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46103.0",
        "DINNER",
        "",
        "Daya",
        "Stacey",
        "Wally",
        "Ben",
        "Donnie",
        "Marijean",
        "Handcrafted Team by Brenda",
      ],
      [
        "46104.0",
        "DINNER",
        "",
        "Marko",
        "Rachel",
        "",
        "Jeanie",
        "Kitty",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
      [
        "46107.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46110.0",
        "BRUNCH",
        "",
        "Marijean",
        "Saje",
        "",
        "Dane",
        "Olive",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46111.0",
        "DINNER",
        "",
        "Ben",
        "Ian",
        "",
        "Frannie",
        "Rachel",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-04",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46114.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46117.0",
        "DINNER",
        "",
        "Christian",
        "Cy",
        "Tyler",
        "Cy",
        "Kitty",
        "Christian",
        "Handcrafted Team by Brenda",
      ],
      [
        "46118.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46121.0",
        "DINNER",
        "",
        "Ash",
        "Marko",
        "Olive",
        "Jeanie",
        "Mark L",
        "Rachel",
        "Handcrafted Team by Brenda",
      ],
      [
        "46125.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46128.0",
        "DINNER",
        "",
        "Alysha",
        "Sandra",
        "Vesanto",
        "Daya",
        "Kitty",
        "Vesanto",
        "Handcrafted Team by Brenda",
      ],
      [
        "46131.0",
        "BRUNCH",
        "",
        "Daya",
        "Nancy",
        "Wally",
        "Laurel",
        "Miriam",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46132.0",
        "DINNER",
        "",
        "Rachel",
        "Mark L",
        "",
        "Alysha",
        "Rose",
        "Saje",
        "Handcrafted Team by Brenda",
      ],
      [
        "46135.0",
        "DINNER",
        "",
        "Marijean",
        "Lorne",
        "Saje",
        "Ben",
        "Ian",
        "Fabrice",
        "Handcrafted Team by Brenda",
      ],
      [
        "46138.0",
        "DINNER",
        "",
        "Ben",
        "Dane",
        "Laurel",
        "Olive",
        "Stacey",
        "Tyler",
        "Handcrafted Team by Brenda",
      ],
      [
        "46139.0",
        "DINNER",
        "",
        "Jeanie",
        "Rose",
        "Stacey",
        "Marko",
        "Nancy",
        "Sandra",
        "Handcrafted Team by Brenda",
      ],
      [
        "46142.0",
        "DINNER",
        "",
        "Ian",
        "Fabrice",
        "",
        "Ash",
        "Frannie",
        "Marijean",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-05",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Clean 4",
        "Clean 5",
        "Clean 6",
        "Clean 7",
        "Clean 8",
        "Clean 9",
        "Status / Notes",
      ],
      [
        "46145.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46146.0",
        "DINNER",
        "",
        "Frannie",
        "Nancy",
        "",
        "Rachel",
        "Rose",
        "Saje",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46149.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46152.0",
        "BRUNCH",
        "",
        "Ash",
        "Stacey",
        "",
        "Ash",
        "Tyler",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46153.0",
        "DINNER",
        "",
        "Ben",
        "Fabrice",
        "",
        "Ian",
        "Kitty",
        "Sandra",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46156.0",
        "DINNER",
        "",
        "Marko",
        "Olive",
        "",
        "Hillary",
        "Jeanie",
        "Marijean",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46159.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46160.0",
        "DINNER",
        "",
        "Ben",
        "Laurel",
        "Vesanto",
        "Brian",
        "Laurel",
        "Vesanto",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46163.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46166.0",
        "BRUNCH",
        "",
        "Hillary",
        "Tyler",
        "",
        "Ian",
        "Frannie",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46167.0",
        "DINNER",
        "",
        "Brian",
        "Jeanie",
        "Sandra",
        "Ben",
        "Fabrice",
        "Marko",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46170.0",
        "DINNER",
        "",
        "Karen",
        "Marijean",
        "Mark L",
        "Kitty",
        "Olive",
        "Wei",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46173.0",
        "DINNER",
        "",
        "Christian",
        "Cy",
        "Rose",
        "Christian",
        "Cy",
        "Nancy",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46145.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46146.0",
        "DINNER",
        "",
        "Frannie",
        "Nancy",
        "",
        "Rachel",
        "Rose",
        "Saje",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46149.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46152.0",
        "BRUNCH",
        "",
        "Ash",
        "Stacey",
        "",
        "Ash",
        "Tyler",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46153.0",
        "DINNER",
        "",
        "Ben",
        "Fabrice",
        "",
        "Ian",
        "Kitty",
        "Sandra",
        "",
        "Marko",
        "Olive",
        "Hillary",
        "Jeanie",
        "Marijean",
        "Handcrafted Team by Brenda",
      ],
      [
        "46159.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46160.0",
        "DINNER",
        "",
        "Ben",
        "Laurel",
        "Vesanto",
        "Brian",
        "Laurel",
        "Vesanto",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46163.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46166.0",
        "BRUNCH",
        "",
        "Hillary",
        "Tyler",
        "",
        "Frannie",
        "Ian",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46167.0",
        "DINNER",
        "",
        "Brian",
        "Jeanie",
        "Sandra",
        "Ben",
        "Fabrice",
        "Marko",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46170.0",
        "DINNER",
        "",
        "Karen",
        "Marijean",
        "Mark L",
        "Kitty",
        "Olive",
        "Wei",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46173.0",
        "DINNER",
        "",
        "Cy",
        "Christian",
        "Rose",
        "Christian",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46076.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46079.0",
        "DINNER",
        "",
        "Monty",
        "Olive",
        "Rachel",
        "Kitty",
        "Paddy",
        "Rachel",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-06",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46174.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46177.0",
        "DINNER",
        "",
        "Marko",
        "Jaela",
        "Brian",
        "Hillary",
        "Jeanie",
        "Sandra",
        "Handcrafted Team by Brenda",
      ],
      [
        "46180.0",
        "DINNER",
        "",
        "Nancy",
        "Rose",
        "",
        "Miriam",
        "Nancy",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
      [
        "46181.0",
        "DINNER",
        "",
        "Mark L",
        "Sandra",
        "Tyler",
        "Brian",
        "Fabrice",
        "Saje",
        "Handcrafted Team by Brenda",
      ],
      [
        "46184.0",
        "DINNER",
        "",
        "Fabrice",
        "Karen",
        "",
        "Marijean",
        "Mark L",
        "Rachel",
        "Handcrafted Team by Brenda",
      ],
      [
        "46187.0",
        "BRUNCH",
        "",
        "Darren",
        "Marijean",
        "",
        "Ash",
        "Darren",
        "Frannie",
        "Handcrafted Team by Brenda",
      ],
      [
        "46188.0",
        "DINNER",
        "",
        "Beth",
        "Frannie",
        "Stacey",
        "Alexandra",
        "Stacey",
        "Tyler",
        "Handcrafted Team by Brenda",
      ],
      [
        "46191.0",
        "DINNER",
        "",
        "Jeanie",
        "Olive",
        "",
        "Hillary",
        "Ian",
        "Marko",
        "Handcrafted Team by Brenda",
      ],
      [
        "46194.0",
        "DINNER",
        "",
        "Christian",
        "Laurel",
        "Saje",
        "Christian",
        "Laurel",
        "Olive",
        "Handcrafted Team by Brenda",
      ],
      [
        "46195.0",
        "DINNER",
        "",
        "Alexandra",
        "Ben",
        "Rachel",
        "Beth",
        "Jaela",
        "Kitty",
        "Handcrafted Team by Brenda",
      ],
      [
        "46198.0",
        "DINNER",
        "",
        "Ian",
        "Vesanto",
        "",
        "Karen",
        "Vesanto",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
      ["46201.0", "BRUNCH", "", "Ash", "Cy", "", "Ben", "Cy", "", "Handcrafted Team by Brenda"],
      [
        "46202.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-07",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46205.0",
        "DINNER",
        "",
        "Fabrice",
        "Frannie",
        "",
        "Kitty",
        "Nancy",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
      [
        "46208.0",
        "DINNER",
        "",
        "Stacey",
        "Brian",
        "",
        "Stacey",
        "Karen",
        "Saje",
        "Handcrafted Team by Brenda",
      ],
      [
        "46209.0",
        "DINNER",
        "",
        "Beth",
        "Lorne",
        "Mark L",
        "Alexandra",
        "Jaela",
        "Tyler",
        "Handcrafted Team by Brenda",
      ],
      [
        "46212.0",
        "DINNER",
        "",
        "Jeanie",
        "Olive",
        "",
        "Lorne",
        "Mark L",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
      [
        "46215.0",
        "BRUNCH",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46216.0",
        "DINNER",
        "",
        "Ash",
        "Sandra",
        "Vesanto",
        "Miriam",
        "Sandra",
        "Vesanto",
        "Handcrafted Team by Brenda",
      ],
      [
        "46219.0",
        "DINNER",
        "",
        "Karen",
        "Saje",
        "Rose",
        "Ben",
        "Tyler",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
      [
        "46222.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46223.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46226.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46229.0",
        "BRUNCH",
        "",
        "Cy",
        "Laurel",
        "",
        "Cy",
        "Laurel",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46230.0",
        "DINNER",
        "",
        "Alexandra",
        "Cam",
        "Nancy",
        "Ash",
        "Cam",
        "Kitty",
        "Handcrafted Team by Brenda",
      ],
      [
        "46233.0",
        "DINNER",
        "",
        "Marko",
        "Ben",
        "",
        "Darren",
        "Frannie",
        "Jeanie",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-08",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46236.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46237.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46240.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46243.0",
        "BRUNCH",
        "",
        "Laurel",
        "Tyler",
        "",
        "Alysha",
        "Laurel",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46244.0",
        "DINNER",
        "",
        "Alex",
        "Mark L",
        "Jaela",
        "Olive",
        "Rachel",
        "Saje",
        "Handcrafted Team by Brenda",
      ],
      [
        "46247.0",
        "DINNER",
        "",
        "Ben",
        "Jeanie",
        "Saje",
        "Ben",
        "Mark L",
        "Marko",
        "Handcrafted Team by Brenda",
      ],
      [
        "46250.0",
        "DINNER",
        "",
        "Brenda",
        "Rose",
        "",
        "Fabrice",
        "Frannie",
        "Nancy",
        "Handcrafted Team by Brenda",
      ],
      [
        "46251.0",
        "DINNER",
        "",
        "Nancy",
        "Stacey",
        "",
        "Jaela",
        "Kitty",
        "Stacey",
        "Handcrafted Team by Brenda",
      ],
      [
        "46254.0",
        "DINNER",
        "",
        "Alysha",
        "Frannie",
        "Ian",
        "Ian",
        "Lorne",
        "Darren",
        "Handcrafted Team by Brenda",
      ],
      ["46257.0", "BRUNCH", "", "Ash", "Cy", "", "Ash", "Cy", "", "Handcrafted Team by Brenda"],
      [
        "46258.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46261.0",
        "DINNER",
        "",
        "Fabrice",
        "Marko",
        "",
        "Alex",
        "Beth",
        "Jeanie",
        "Handcrafted Team by Brenda",
      ],
      [
        "46264.0",
        "DINNER",
        "",
        "Christian",
        "Lorne",
        "Olive",
        "Christian",
        "Miriam",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
      [
        "46265.0",
        "DINNER",
        "",
        "Beth",
        "Rachel",
        "Vesanto",
        "Rose",
        "Vesanto",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
  {
    monthKey: "2026-09",
    rows: [
      [
        "Date",
        "Meal Type",
        "Special Note",
        "Cook 1",
        "Cook 2",
        "Cook 3",
        "Cook 4",
        "Clean 1",
        "Clean 2",
        "Clean 3",
        "Status / Notes",
      ],
      [
        "46268.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46271.0",
        "DINNER",
        "",
        "Alexandra",
        "Christian",
        "Lorne",
        "",
        "Christian",
        "Ian",
        "Tyler",
        "Handcrafted Team by Brenda",
      ],
      [
        "46272.0",
        "DINNER",
        "",
        "Frannie",
        "Laurel",
        "Mark L",
        "",
        "Beth",
        "Kitty",
        "Rose",
        "Handcrafted Team by Brenda",
      ],
      [
        "46275.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46278.0",
        "BRUNCH",
        "",
        "Stacey",
        "Tyler",
        "",
        "",
        "Ben",
        "Kitty",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46279.0",
        "DINNER",
        "",
        "Ben",
        "Fabrice",
        "",
        "",
        "Darren",
        "Miriam",
        "Nancy",
        "Handcrafted Team by Brenda",
      ],
      [
        "46282.0",
        "DINNER",
        "NO COMMUNITY MEAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46285.0",
        "DINNER",
        "",
        "Brenda",
        "Nancy",
        "",
        "",
        "Alexandra",
        "Brenda",
        "Dane",
        "Handcrafted Team by Brenda",
      ],
      [
        "46286.0",
        "DINNER",
        "",
        "Ian",
        "Janco",
        "Wei",
        "",
        "Darren",
        "Frannie",
        "Kitty",
        "Handcrafted Team by Brenda",
      ],
      [
        "46289.0",
        "DINNER",
        "",
        "Olive",
        "Rose",
        "Saje",
        "",
        "Janco",
        "Rachel",
        "Stacey",
        "Handcrafted Team by Brenda",
      ],
      [
        "46292.0",
        "BRUNCH",
        "",
        "Cy",
        "Dane",
        "",
        "",
        "Cy",
        "Laurel",
        "",
        "Handcrafted Team by Brenda",
      ],
      [
        "46293.0",
        "DINNER",
        "",
        "Alysha",
        "Beth",
        "Daya",
        "Vesanto",
        "Alysha",
        "Vesanto",
        "Wei",
        "Handcrafted Team by Brenda",
      ],
    ],
  },
];

export function getBaselineHistoricalSchedules(): MonthScheduleRecord[] {
  const records: MonthScheduleRecord[] = [];
  for (const item of RAW_HISTORICAL_GRIDS) {
    const parsed = parseScheduleGridData(item.rows);
    if (parsed.success && parsed.schedule.length > 0) {
      records.push({
        monthKey: item.monthKey,
        monthLabel: item.monthKey,
        schedule: parsed.schedule,
      });
    }
  }
  return records;
}
